# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_auto_20150916_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Администратор',
                'ordering': ['order'],
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=model_utils.fields.StatusField(default='planning', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='status',
            field=model_utils.fields.StatusField(default='active', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
